test api via fichier python

diff --git a/.github/workflows/docker_test.yml b/.github/workflows/docker_test.yml
--- a/.github/workflows/docker_test.yml
+++ b/.github/workflows/docker_test.yml
@@ -12,6 +12,9 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Install Python dependencies
+        run: pip install -r requirements_env_test.txt
+
       - name: Build Docker
         run: |
           docker build -t fastapi-whisper .
@@ -21,14 +24,17 @@ jobs:
           docker run -d --name fastapi-whisper_conteneur -p 7860:7860 fastapi-whisper
           sleep 60
 
-      - name: Test endpoint
-        run: |
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7860/docs)
-          if [ "$RESPONSE" -ne 200 ]; then
-            echo "API test failed!"
-            docker logs fastapi-whisper_conteneur
-            exit 1
-          fi
+      - name: Test API in Python
+        run: python test_api.py
+
+    #   - name: Test endpoint
+    #     run: |
+    #       RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7860/docs)
+    #       if [ "$RESPONSE" -ne 200 ]; then
+    #         echo "API test failed!"
+    #         docker logs fastapi-whisper_conteneur
+    #         exit 1
+    #       fi
 
       - name: Stop container
         run: docker stop fastapi-whisper_conteneur
